[general]
caption_extension = ".txt"
batch_size = 1
enable_bucket = true
bucket_no_upscale = false

[[datasets]]
video_jsonl_file = "/data/RealCam-Vid/DL3DV-10K.jsonl"
target_frames = [129]
frame_extraction = "uniform"
cache_directory = "/data/RealCam-Vid/cache/DL3DV-10K"
resolution = [960, 540]

[[datasets]]
video_jsonl_file = "/data/RealCam-Vid/MiraData9K.jsonl"
target_frames = [129]
frame_extraction = "uniform"
cache_directory = "/data/RealCam-Vid/cache/MiraData9K"
resolution = [1280, 720]

[[datasets]]
video_jsonl_file = "/data/RealCam-Vid/RealEstate10K.jsonl"
target_frames = [77]
frame_extraction = "uniform"
cache_directory = "/data/RealCam-Vid/cache/RealEstate10K"
resolution = [1920, 1088]
